version: "3.7"

services: 

  icontracts:
    build: ./flask
    container_name: icontracts
    restart: always
    environment:
      - APP_NAME=iContractsApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"